version: '3.4'

services:

  api:
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    ports:
      - "8400:80"
    env_file: .env

  functions:
    build:
      context: ./src
      dockerfile: Functions/Dockerfile
    env_file: .env